language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
            - doxygen
            - libudev-dev
            - libfreetype6-dev
            - libx11-6
            - libxrandr-dev
            - xcb
            - libx11-xcb-dev
            - libxcb-randr0-dev
            - libxcb-image0-dev
            - libflac++-dev
            - oggconvert
            - libvorbis-dev
            - libvorbisenc2
            - libvorbisfile3
            - libopenal-dev

      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build & cd build
  - cmake .. && make -j $(nproc --all)
  - doxygen

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: "docs"
